### ISSUE TITLE
The function of the plugin will cause the highlighting function of the search to be unavailable.

### ISSUE THREAD

**Issue by zhaihao** [twibiral/obsidian-execute-code#242]
<img width="644" alt="截屏2023-03-28 22 42 24" src="https://user-images.githubusercontent.com/4202032/228276441-96efcb2c-3d91-4128-955d-8d467cfa0e8a.png">

**Comment by zhaihao** [comment]
to fix this problem via css
```css
.markdown-rendered .search-highlight > div {
    mix-blend-mode: normal;
    background-blend-mode: normal;
}

.markdown-rendered .search-highlight > div.is-active {
    mix-blend-mode: normal;
    background-blend-mode: normal;
}
```
